spring:
  cloud:
    nacos:
      server-addr: 47.110.84.227:8848
      discovery:
        namespace: 11f7f8bf-18d6-4527-aac0-771d68803426
      config:
        namespace: 11f7f8bf-18d6-4527-aac0-771d68803426
        file-extension: yaml
        refresh-enabled: true
  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}