spring:
  cloud:
    nacos:
      #server-addr: 127.0.0.1:8848
      server-addr: 192.168.88.132:8848
      config:
        file-extension: yaml
        refresh-enabled: true
  config:
    import:
      - nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
      - nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
